version: '2'
services:
  zookeeper:
    container_name: snnLab-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: snnLab-kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "snnLab:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  rabbitmq:
    container_name: snnLab-rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672" #JMS Port
      - "15672:15672"