spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    prop:
      snnlab:
        exchange: snnLab-exchange
        queue: snnLab-queue
        routingKey: snnLab


kafka:
  bindAddress: localhost:9092
  #bindAddress: localhost:9092


